// Codegen: read plugins/*/plugin.json and emit src/plugins/api.gen.ts.
//
// Each command declared in plugin.json becomes a typed wrapper that calls
// `invoke<T>('dispatch', { name, args })` under the hood, so the frontend gets
// type-safe access to backend commands without any hand-written boilerplate.
//
// Run via `npm run codegen`, or automatically via `predev` / `prebuild`.
// Implemented in plain JS so it works without a TS runtime dependency.

const { readFileSync, writeFileSync, readdirSync, existsSync } = require('node:fs');
const { resolve, join } = require('node:path');

const ROOT = resolve(__dirname, '..');
const PLUGINS_DIR = join(ROOT, 'plugins');
const OUT_PATH = join(ROOT, 'src', 'plugins', 'api.gen.ts');

function toCamel(s) {
  // "port-manager" / "kill_by_process_name" → "portManager" / "killByProcessName".
  // Split on any non-alphanumeric char, then join in camelCase.
  return s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part, i) =>
      i === 0
        ? part[0].toLowerCase() + part.slice(1)
        : part[0].toUpperCase() + part.slice(1),
    )
    .join('');
}

function loadPlugins() {
  if (!existsSync(PLUGINS_DIR)) return [];
  const result = [];
  for (const dir of readdirSync(PLUGINS_DIR, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue;
    const manifestPath = join(PLUGINS_DIR, dir.name, 'plugin.json');
    if (!existsSync(manifestPath)) continue;
    try {
      const raw = JSON.parse(readFileSync(manifestPath, 'utf-8'));
      result.push(raw);
    } catch (e) {
      console.warn(`[codegen] ${dir.name}/plugin.json: ${e.message}`);
    }
  }
  return result;
}

function emit(plugins) {
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/codegen-api.cjs — DO NOT EDIT.');
  lines.push('// Regenerate with `npm run codegen`.');
  lines.push('/* eslint-disable */');
  lines.push('');
  lines.push("import { invoke } from '@tauri-apps/api/core';");

  // Collect every distinct type referenced in argsRef / returnsRef so we can
  // emit a single import for all of them.
  const typeNames = new Set();
  for (const plugin of plugins) {
    for (const cmd of plugin.commands ?? []) {
      if (cmd.argsRef && cmd.argsRef !== 'void') typeNames.add(cmd.argsRef);
      if (cmd.returnsRef && cmd.returnsRef !== 'void') typeNames.add(cmd.returnsRef);
    }
  }
  if (typeNames.size > 0) {
    const sorted = Array.from(typeNames).sort();
    lines.push(`import type { ${sorted.join(', ')} } from '../types';`);
  }
  lines.push('');
  lines.push('// Helper: route a typed call through the `dispatch` Tauri command.');
  lines.push('function dispatch<T>(name: string, args: object = {}): Promise<T> {');
  lines.push("  return invoke<T>('dispatch', { name, args });");
  lines.push('}');
  lines.push('');

  if (plugins.length === 0) {
    lines.push('// No plugins found under plugins/. Add a folder with plugin.json.');
    return lines.join('\n') + '\n';
  }

  for (const plugin of plugins) {
    const commands = plugin.commands ?? [];
    if (commands.length === 0) continue;
    lines.push(`// --- ${plugin.id} ---`);
    lines.push(`export const ${toCamel(plugin.id)}Api = {`);
    for (const cmd of commands) {
      const methodName = toCamel(cmd.name);
      const argsType = cmd.argsRef ?? 'void';
      const returnsType = cmd.returnsRef ?? 'void';
      const isVoid = argsType === 'void';
      const argExpr = isVoid ? '' : `args: ${argsType} = {} as ${argsType}`;
      lines.push(`  ${methodName}: (${argExpr}): Promise<${returnsType}> =>`);
      lines.push(`    dispatch<${returnsType}>('${cmd.name}', ${isVoid ? '{}' : 'args'}),`);
    }
    lines.push('};');
    lines.push('');
  }

  return lines.join('\n');
}

function main() {
  const plugins = loadPlugins();
  const output = emit(plugins);
  writeFileSync(OUT_PATH, output, 'utf-8');
  console.log(
    `[codegen] wrote ${OUT_PATH.replace(ROOT + '\\', '')} (${plugins.length} plugin(s))`,
  );
}

main();
